spring.application.name=system

# Railway DATABASE_URL එක 'jdbc:' සමඟ හරියටම මැච් කරගැනීම
spring.datasource.url=jdbc:${DATABASE_URL}

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true